name: gradle build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      
      # https://github.com/mknejp/delete-release-assets
      - uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          fail-if-no-assets: false
          fail-if-no-release: false
          tag: latest
          assets: |
                  ./app/build/outputs/apk/release/app-release-unsigned.apk

      # https://github.com/softprops/action-gh-release
      - run: cat apk
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./app/build/outputs/apk/release/app-release-unsigned.apk
          tag_name: "latest"
          prerelease: true      
